import { randomUUID } from "node:crypto";
import {
  reviewedExecutionPreparationSchema,
  reviewedExecutionPrepareRequestSchema,
  reviewedExecutionRecordRequestSchema,
  type BridgeApplyResult,
  type BridgePatchPlanView,
  type BridgeTransactionApplyResult,
  type HumanReviewRequest,
  type ReviewedDocumentComparison,
  type ReviewedExecutionComparison,
  type ReviewedExecutionPreparation,
  type ReviewedExecutionPrepareRequest,
  type ReviewedExecutionRecordRequest,
  type ReviewedExecutionSourceResult,
  type ReviewedSourceComparison,
  type SemanticPlanView,
} from "@afrodite/protocol";
import { createSemanticDocumentVersion } from "@afrodite/semantic-ops";
import {
  ProjectCollaborationError,
  type ProjectCollaborationStore,
} from "./collaboration.js";
import { planProjectSemanticOperationBundle } from "./semantic.js";
import type { ProjectBridgeService } from "./service.js";

export interface ReviewedExecutionServiceOptions {
  readonly collaboration: ProjectCollaborationStore;
  readonly projectBridge: ProjectBridgeService;
  readonly now?: () => number;
  readonly idFactory?: () => string;
}

export class ReviewedExecutionService {
  readonly #collaboration: ProjectCollaborationStore;
  readonly #projectBridge: ProjectBridgeService;
  readonly #now: () => number;
  readonly #idFactory: () => string;

  constructor(options: ReviewedExecutionServiceOptions) {
    this.#collaboration = options.collaboration;
    this.#projectBridge = options.projectBridge;
    this.#now = options.now ?? Date.now;
    this.#idFactory = options.idFactory ?? randomUUID;
  }

  async prepare(input: ReviewedExecutionPrepareRequest): Promise<HumanReviewRequest> {
    const request = reviewedExecutionPrepareRequestSchema.parse(input);
    const review = await this.#collaboration.getReview(request.requestId);
    if (review.status !== "approved") {
      throw new ProjectCollaborationError(
        "REVIEW_EXECUTION_NOT_APPROVED",
        "Only an approved review request can be prepared for execution.",
      );
    }
    if (
      review.execution
      && ["applied", "document-only", "source-only"].includes(review.execution.status)
    ) {
      throw new ProjectCollaborationError(
        "REVIEW_ALREADY_EXECUTED",
        `Review request ${review.requestId} already has terminal execution ${review.execution.executionId}.`,
      );
    }

    const live = await this.#collaboration.readSession();
    const fresh = await planProjectSemanticOperationBundle(
      this.#projectBridge,
      live.document,
      review.command,
    );
    const changedPlans = fresh.plan.sourcePlans.filter((plan) => plan.changed);
    if (changedPlans.length > 1 && !fresh.transaction) {
      throw new ProjectCollaborationError(
        "REVIEW_TRANSACTION_REQUIRED",
        "A fresh preparation with several changed source files must be bound to one bridge transaction.",
      );
    }
    if (fresh.transaction && fresh.transaction.changedFiles !== changedPlans.length) {
      throw new ProjectCollaborationError(
        "REVIEW_TRANSACTION_PLAN_MISMATCH",
        "The fresh transaction does not contain every changed source effect from the semantic plan.",
      );
    }

    const preparation = reviewedExecutionPreparationSchema.parse({
      preparationId: `preparation_${this.#idFactory()}`,
      preparedAt: new Date(this.#now()).toISOString(),
      preparedBy: request.preparedBy,
      liveSessionId: live.sessionId,
      liveRevision: live.revision,
      liveDocumentVersion: live.documentVersion,
      plan: fresh.plan,
      comparison: compareReviewedEffects(review, fresh.plan),
      ...(fresh.transaction ? { transaction: fresh.transaction } : {}),
    });
    return this.#collaboration.saveExecutionPreparation(review.requestId, preparation);
  }

  async record(input: ReviewedExecutionRecordRequest): Promise<HumanReviewRequest> {
    const request = reviewedExecutionRecordRequestSchema.parse(input);
    const review = await this.#collaboration.getReview(request.requestId);
    const preparation = review.preparation;
    if (!preparation || preparation.preparationId !== request.preparationId) {
      throw new ProjectCollaborationError(
        "REVIEW_PREPARATION_MISMATCH",
        "The execution does not reference the latest prepared plan.",
      );
    }

    if (preparation.transaction) {
      if (!request.transactionResult) {
        throw new ProjectCollaborationError(
          "REVIEW_TRANSACTION_RESULT_REQUIRED",
          "A multi-file preparation must record its shared transaction result.",
        );
      }
      if (request.sourceResults.length > 0) {
        throw new ProjectCollaborationError(
          "REVIEW_TRANSACTION_SOURCE_RESULTS_FORGED",
          "Per-file results for a reviewed transaction are generated by the project bridge, not the browser.",
        );
      }
      const sourceResults = normalizeTransactionSourceResults(
        preparation,
        request.transactionResult,
      );
      return this.#collaboration.recordExecution({
        ...request,
        sourceResults,
      });
    }

    if (request.transactionResult) {
      throw new ProjectCollaborationError(
        "REVIEW_TRANSACTION_RESULT_UNEXPECTED",
        "This fresh preparation is not a multi-file transaction.",
      );
    }
    return this.#collaboration.recordExecution(request);
  }
}

export function compareReviewedEffects(
  review: HumanReviewRequest,
  freshPlan: SemanticPlanView,
): ReviewedExecutionComparison {
  const document = compareDocuments(review, freshPlan);
  const sources = compareSources(review.sourcePlans, freshPlan.sourcePlans);
  const applicationModeMatches = review.applicationMode === freshPlan.applicationMode;
  const exactMatch = freshPlan.status === "ready"
    && applicationModeMatches
    && (document.status === "none" || document.status === "identical")
    && sources.every((source) => source.status === "identical");

  let summary: string;
  if (freshPlan.status !== "ready") {
    summary = `Fresh planning returned ${freshPlan.status}; execution is blocked until the semantic command becomes ready.`;
  } else if (exactMatch) {
    summary = "Fresh planning reproduced the exact reviewed document and source effects.";
  } else {
    const changedSources = sources.filter((source) => source.status !== "identical").length;
    const documentChanged = document.status !== "none" && document.status !== "identical";
    summary = `Fresh planning differs from the approved snapshot${documentChanged ? " in the document effect" : ""}${documentChanged && changedSources ? " and" : ""}${changedSources ? ` in ${changedSources} source effect${changedSources === 1 ? "" : "s"}` : ""}. Review the fresh result before execution.`;
  }

  return {
    exactMatch,
    applicationModeMatches,
    document,
    sources,
    summary,
  };
}

function normalizeTransactionSourceResults(
  preparation: ReviewedExecutionPreparation,
  result: BridgeTransactionApplyResult,
): ReviewedExecutionSourceResult[] {
  const transaction = preparation.transaction!;
  if (result.transactionId !== transaction.transactionId) {
    throw new ProjectCollaborationError(
      "REVIEW_TRANSACTION_RESULT_MISMATCH",
      "The transaction result does not match the latest reviewed transaction ID.",
    );
  }

  const changedPlans = preparation.plan.sourcePlans
    .filter((plan) => plan.changed)
    .sort((left, right) => left.repositoryPath.localeCompare(right.repositoryPath));
  const transactionFiles = uniqueByPath(transaction.files, "REVIEW_TRANSACTION_PLAN_DUPLICATE");
  if (transactionFiles.size !== changedPlans.length || transaction.changedFiles !== changedPlans.length) {
    throw new ProjectCollaborationError(
      "REVIEW_TRANSACTION_PLAN_MISMATCH",
      "The reviewed transaction does not contain exactly the fresh changed source plans.",
    );
  }

  for (const plan of changedPlans) {
    const file = transactionFiles.get(plan.repositoryPath);
    if (
      !file
      || !file.changed
      || file.planId !== plan.planId
      || file.sourceVersion !== plan.sourceVersion
    ) {
      throw new ProjectCollaborationError(
        "REVIEW_TRANSACTION_PLAN_MISMATCH",
        `The transaction file ${plan.repositoryPath} does not match its fresh plan and source version.`,
      );
    }
  }

  const resultFiles = uniqueByPath(result.files, "REVIEW_TRANSACTION_RESULT_DUPLICATE");
  for (const repositoryPath of resultFiles.keys()) {
    if (!transactionFiles.has(repositoryPath)) {
      throw new ProjectCollaborationError(
        "REVIEW_TRANSACTION_RESULT_MISMATCH",
        `The transaction result contains an unexpected file ${repositoryPath}.`,
      );
    }
  }
  if (result.status === "applied" && resultFiles.size !== changedPlans.length) {
    throw new ProjectCollaborationError(
      "REVIEW_TRANSACTION_RESULT_INCOMPLETE",
      "An applied transaction must contain a result for every reviewed source file.",
    );
  }

  return changedPlans.map((plan, index) => {
    const file = resultFiles.get(plan.repositoryPath);
    const status = perFileTransactionStatus(result.status, file);
    const normalized: BridgeApplyResult = {
      status,
      planId: plan.planId,
      beforeVersion: file?.beforeVersion ?? plan.sourceVersion,
      ...(file?.afterVersion ? { afterVersion: file.afterVersion } : {}),
      ...(file?.restoredVersion ? { restoredVersion: file.restoredVersion } : {}),
      diagnostics: result.diagnostics.map((diagnostic) => ({ ...diagnostic })),
      verification: result.verification.map((execution) => ({
        ...execution,
        step: { ...execution.step },
      })),
    };
    return {
      planId: plan.planId,
      repositoryPath: plan.repositoryPath,
      sourceVersion: plan.sourceVersion,
      result: normalized,
      transactionId: result.transactionId,
      ...(index === 0 ? { transactionResult: result } : {}),
    };
  });
}

function perFileTransactionStatus(
  transactionStatus: BridgeTransactionApplyResult["status"],
  file: BridgeTransactionApplyResult["files"][number] | undefined,
): BridgeApplyResult["status"] {
  if (transactionStatus !== "rollback-failed") return transactionStatus;
  if (file?.restoredVersion) return "rolled-back";
  if (file?.afterVersion) return "applied";
  return "rollback-failed";
}

function uniqueByPath<T extends { readonly repositoryPath: string }>(
  entries: readonly T[],
  code: string,
): Map<string, T> {
  const result = new Map<string, T>();
  for (const entry of entries) {
    if (result.has(entry.repositoryPath)) {
      throw new ProjectCollaborationError(
        code,
        `More than one transaction entry references ${entry.repositoryPath}.`,
      );
    }
    result.set(entry.repositoryPath, entry);
  }
  return result;
}

function compareDocuments(
  review: HumanReviewRequest,
  freshPlan: SemanticPlanView,
): ReviewedDocumentComparison {
  const approved = review.documentAfter;
  const fresh = freshPlan.documentAfter;
  if (!approved && !fresh) return { status: "none" };
  if (!approved && fresh) {
    return {
      status: "added",
      freshDocumentVersion: createSemanticDocumentVersion(fresh),
    };
  }
  if (approved && !fresh) {
    return {
      status: "removed",
      approvedDocumentVersion: createSemanticDocumentVersion(approved),
    };
  }
  const approvedDocumentVersion = createSemanticDocumentVersion(approved!);
  const freshDocumentVersion = createSemanticDocumentVersion(fresh!);
  return {
    status: approvedDocumentVersion === freshDocumentVersion ? "identical" : "changed",
    approvedDocumentVersion,
    freshDocumentVersion,
  };
}

function compareSources(
  approvedPlans: readonly BridgePatchPlanView[],
  freshPlans: readonly BridgePatchPlanView[],
): ReviewedSourceComparison[] {
  const approved = [...approvedPlans].sort(comparePlanIdentity);
  const fresh = [...freshPlans].sort(comparePlanIdentity);
  const paths = [...new Set([
    ...approved.map((plan) => plan.repositoryPath),
    ...fresh.map((plan) => plan.repositoryPath),
  ])].sort();
  const comparisons: ReviewedSourceComparison[] = [];

  for (const repositoryPath of paths) {
    const approvedAtPath = approved.filter((plan) => plan.repositoryPath === repositoryPath);
    const freshAtPath = fresh.filter((plan) => plan.repositoryPath === repositoryPath);
    const count = Math.max(approvedAtPath.length, freshAtPath.length);
    for (let index = 0; index < count; index += 1) {
      const approvedPlan = approvedAtPath[index];
      const freshPlan = freshAtPath[index];
      if (!approvedPlan && freshPlan) {
        comparisons.push({
          repositoryPath,
          status: "added",
          freshPlanId: freshPlan.planId,
          freshSourceVersion: freshPlan.sourceVersion,
        });
      } else if (approvedPlan && !freshPlan) {
        comparisons.push({
          repositoryPath,
          status: "removed",
          approvedPlanId: approvedPlan.planId,
          approvedSourceVersion: approvedPlan.sourceVersion,
        });
      } else if (approvedPlan && freshPlan) {
        comparisons.push({
          repositoryPath,
          status: sameSourceEffect(approvedPlan, freshPlan) ? "identical" : "changed",
          approvedPlanId: approvedPlan.planId,
          freshPlanId: freshPlan.planId,
          approvedSourceVersion: approvedPlan.sourceVersion,
          freshSourceVersion: freshPlan.sourceVersion,
        });
      }
    }
  }
  return comparisons;
}

function sameSourceEffect(
  approved: BridgePatchPlanView,
  fresh: BridgePatchPlanView,
): boolean {
  return JSON.stringify(normalizeSourceEffect(approved)) === JSON.stringify(normalizeSourceEffect(fresh));
}

function normalizeSourceEffect(plan: BridgePatchPlanView) {
  return {
    repositoryPath: plan.repositoryPath,
    sourceVersion: plan.sourceVersion,
    changed: plan.changed,
    diff: plan.diff,
    diagnostics: plan.diagnostics,
    verification: plan.verification,
  };
}

function comparePlanIdentity(left: BridgePatchPlanView, right: BridgePatchPlanView): number {
  return left.repositoryPath.localeCompare(right.repositoryPath)
    || left.planId.localeCompare(right.planId);
}
